### ISSUE TITLE
AttributeError: module 'knapsack' has no attribute 'ECTNew'

### ISSUE THREAD

**Issue by christophsk** [adamlechowicz/fair-knapsack#1]
Changing to `return k.ECT(*args)[0][-1]` seems to work.

Trace:
```
(base) me fair-knapsack (main) $ python experiments.py
Loaded traces from pickle file
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/me/miniforge3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/me/miniforge3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/me/pycharm_projects/fair-knapsack/experiments.py", line 29, in ECT_unpack
    return k.ECTNew(*args)[0][-1] # profit is returned over time, so just get the final profit
AttributeError: module 'knapsack' has no attribute 'ECTNew'
```

**Comment by adamlechowicz** [comment]
Thanks for catching this!  This was indeed a typo, and `return k.ECT(*args)[0][-1]` is correct.  I will push a fix.  Please let me know if you find any other issues!
